import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import CardSwap, { Card } from '../components/CardSwap';
import { FloatingPaths } from '../components/FloatingPaths';

const KairoLogo = () => (
  <svg width="24" height="24" viewBox="0 0 100 100" fill="none">
    <defs>
      <linearGradient id="kgd" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stopColor="#9B7FFF" />
        <stop offset="100%" stopColor="#00CFFF" />
      </linearGradient>
    </defs>
    <rect x="15" y="10" width="16" height="80" rx="4" fill="url(#kgd)" />
    <path d="M31 50 L72 10 L90 10 L49 50Z" fill="url(#kgd)" />
    <path d="M31 50 L72 90 L90 90 L49 50Z" fill="url(#kgd)" opacity="0.9" />
    <rect x="55" y="47" width="28" height="3" rx="1.5" fill="url(#kgd)" opacity="0.5" />
    <rect x="60" y="53" width="20" height="2" rx="1" fill="url(#kgd)" opacity="0.3" />
  </svg>
);

function WeeklyChart({ data }) {
  const max = Math.max(...data.map(d => d.completed), 1);
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: '8px', height: '80px', padding: '0 4px' }}>
      {data.map((d, i) => {
        const isToday = i === data.length - 1;
        const height = Math.max((d.completed / max) * 100, d.completed > 0 ? 8 : 4);
        return (
          <div key={d.date} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '5px' }}>
            <div style={{ fontSize: '0.65rem', color: d.completed > 0 ? '#9B7FFF' : 'rgba(255,255,255,0.2)', fontWeight: 600 }}>
              {d.completed > 0 ? d.completed : ''}
            </div>
            <div style={{ width: '100%', position: 'relative', height: '55px', display: 'flex', alignItems: 'flex-end' }}>
              <motion.div
                initial={{ height: 0 }}
                animate={{ height: `${height}%` }}
                transition={{ delay: i * 0.06, duration: 0.5, ease: 'easeOut' }}
                style={{
                  width: '100%', borderRadius: '4px 4px 2px 2px',
                  background: isToday
                    ? 'linear-gradient(180deg,#9B7FFF,#00CFFF)'
                    : d.completed > 0
                      ? 'rgba(155,127,255,0.35)'
                      : 'rgba(255,255,255,0.06)',
                  border: isToday ? 'none' : '1px solid rgba(255,255,255,0.05)',
                  minHeight: '4px'
                }}
              />
            </div>
            <div style={{ fontSize: '0.62rem', color: isToday ? '#9B7FFF' : 'rgba(255,255,255,0.25)', fontWeight: isToday ? 700 : 400 }}>
              {isToday ? 'Today' : d.day}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function StreakBadge({ streak }) {
  const msg = streak >= 7 ? '🔥 On fire!' : streak >= 3 ? '⚡ Building momentum' : streak >= 1 ? '✨ Getting started' : '💤 Start your streak';
  const color = streak >= 7 ? '#FF6B35' : streak >= 3 ? '#9B7FFF' : streak >= 1 ? '#00CFFF' : 'rgba(255,255,255,0.3)';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 14px', background: `${color}12`, border: `1px solid ${color}28`, borderRadius: '10px' }}>
      <div style={{ fontSize: '1.4rem' }}>{streak >= 7 ? '🔥' : streak >= 3 ? '⚡' : streak >= 1 ? '✨' : '💤'}</div>
      <div>
        <div style={{ fontSize: '0.85rem', fontWeight: 700, color }}>{streak} day streak</div>
        <div style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.35)' }}>{msg}</div>
      </div>
    </div>
  );
}

export default function Dashboard({ user, onLogout }) {
  const [tasks, setTasks] = useState([]);
  const [newTask, setNewTask] = useState('');
  const [deadline, setDeadline] = useState('');
  const [activePage, setActivePage] = useState('tasks');
  const [focusTask, setFocusTask] = useState(null);
  const [timer, setTimer] = useState(0);
  const [timerRunning, setTimerRunning] = useState(false);
  const [toasts, setToasts] = useState([]);
  const [weeklyStats, setWeeklyStats] = useState([]);
  const [deletingId, setDeletingId] = useState(null);
  const [recommendations, setRecommendations] = useState([]);
  const [recsLoading, setRecsLoading] = useState(false);
  const [recsGenerated, setRecsGenerated] = useState(false);
  const [autoSteps, setAutoSteps] = useState([]);
  const [autoLoading, setAutoLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [autoInput, setAutoInput] = useState('');
  const [autoGoal, setAutoGoal] = useState('');
  const [allNotifications, setAllNotifications] = useState([]);
  const [showNotifPanel, setShowNotifPanel] = useState(false);
  const [unreadCount, setUnreadCount] = useState(0);

  const [messages, setMessages] = useState([
    { role: 'assistant', text: `Hey ${user.name}! 👋 I'm Kairo. Tell me about your day — what do you need to get done?` }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const [aiPlan, setAiPlan] = useState(null);
  const [isListening, setIsListening] = useState(false);
  const [voiceSupported, setVoiceSupported] = useState(false);
  const [isProcessingVoice, setIsProcessingVoice] = useState(false);

  const recognitionRef = useRef(null);
  const chatEndRef = useRef(null);
  const speakingRef = useRef(false);
  const notifiedRef = useRef(new Set());

  const token = localStorage.getItem('kairo_token');
  const headers = { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` };

  function addToast(msg, type = 'info') {
  const id = Date.now();
  const notif = { id, msg, type, time: new Date(), read: false };
  setToasts(prev => [...prev.slice(-2), notif]);
  setAllNotifications(prev => [notif, ...prev.slice(0, 49)]);
  setUnreadCount(prev => prev + 1);
  setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 6000);
}

  useEffect(() => {
    fetch('https://kairo-isfu.onrender.com/api/tasks', { headers })
      .then(r => r.json()).then(data => { if (Array.isArray(data)) setTasks(data); })
      .catch(console.error);
    fetch('https://kairo-isfu.onrender.com/api/tasks/weekly-stats', { headers })
      .then(r => r.json()).then(data => { if (Array.isArray(data)) setWeeklyStats(data); })
      .catch(console.error);
    if ('Notification' in window && Notification.permission === 'default') {
      Notification.requestPermission();
    }
  }, []);

  useEffect(() => {
    function checkDeadlines() {
      const now = new Date();
      tasks.filter(t => t.status === 'pending' && t.deadline).forEach(task => {
        const dl = new Date(task.deadline);
        const msLeft = dl - now;
        const minsLeft = Math.round(msLeft / 60000);
        if (msLeft < 0) return;
        const k30 = `${task.id}-30`, k120 = `${task.id}-120`;
        if (minsLeft <= 30 && !notifiedRef.current.has(k30)) {
          notifiedRef.current.add(k30);
          const msg = `🚨 "${task.title}" is due in ${minsLeft} minutes!`;
          addToast(msg, 'urgent');
          if (Notification.permission === 'granted') new Notification('Kairo — Urgent', { body: msg });
        } else if (minsLeft <= 120 && minsLeft > 30 && !notifiedRef.current.has(k120)) {
          notifiedRef.current.add(k120);
          const msg = `🔔 "${task.title}" is due in ~${Math.round(minsLeft / 60 * 10) / 10}h`;
          addToast(msg, 'warning');
          if (Notification.permission === 'granted') new Notification('Kairo — Reminder', { body: msg });
        }
      });
    }
    checkDeadlines();
    const iv = setInterval(checkDeadlines, 60000);
    return () => clearInterval(iv);
  }, [tasks]);

  useEffect(() => {
    let iv;
    if (timerRunning) iv = setInterval(() => setTimer(t => t + 1), 1000);
    return () => clearInterval(iv);
  }, [timerRunning]);

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, chatLoading]);

  useEffect(() => {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SR) {
      setVoiceSupported(true);
      const r = new SR();
      r.continuous = false; r.interimResults = false; r.lang = 'en-US';
      r.onresult = async (e) => {
        const t = e.results[0][0].transcript;
        setIsListening(false); setIsProcessingVoice(true); setChatInput(t);
        await handleSendMessage(t); setIsProcessingVoice(false);
      };
      r.onerror = () => { setIsListening(false); setIsProcessingVoice(false); };
      r.onend = () => setIsListening(false);
      recognitionRef.current = r;
    }
  }, []);

  // Compute streak from weekly stats
  const streak = (() => {
    let s = 0;
    const sorted = [...weeklyStats].reverse();
    for (const d of sorted) {
      if (d.completed > 0) s++;
      else break;
    }
    return s;
  })();

  const totalThisWeek = weeklyStats.reduce((a, d) => a + d.completed, 0);
  const bestDay = weeklyStats.reduce((a, d) => d.completed > a.completed ? d : a, { completed: 0, day: '-' });

  function toggleVoice() {
    if (!recognitionRef.current) return;
    if (isListening) { recognitionRef.current.stop(); setIsListening(false); }
    else { setChatInput(''); recognitionRef.current.start(); setIsListening(true); }
  }

  function speakText(text) {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel(); speakingRef.current = true;
    const clean = text.replace(/[*_#`]/g, '').replace(/\n+/g, ' ').trim();
    const sentences = clean.match(/[^.!?]+[.!?]+/g) || [clean];
    let idx = 0;
    function next() {
      if (!speakingRef.current || idx >= sentences.length) return;
      const u = new SpeechSynthesisUtterance(sentences[idx].trim());
      u.rate = 1.05; u.pitch = 1; u.volume = 1;
      const vs = window.speechSynthesis.getVoices();
      const v = vs.find(v => v.name.includes('Google') && v.lang === 'en-US') || vs.find(v => v.lang === 'en-US') || vs[0];
      if (v) u.voice = v;
      u.onend = () => { if (!speakingRef.current) return; idx++; next(); };
      u.onerror = () => { if (!speakingRef.current) return; idx++; next(); };
      window.speechSynthesis.speak(u);
    }
    const ri = setInterval(() => {
      if (!speakingRef.current) { clearInterval(ri); return; }
      if (window.speechSynthesis.paused) window.speechSynthesis.resume();
      if (!window.speechSynthesis.speaking) clearInterval(ri);
    }, 5000);
    next();
  }

  function stopSpeaking() { speakingRef.current = false; window.speechSynthesis.cancel(); }

  async function handleSendMessage(text) {
    const userMsg = (text || chatInput).trim();
    if (!userMsg || chatLoading) return;
    setChatInput('');
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setChatLoading(true);
    try {
      const res = await fetch('https://kairo-isfu.onrender.com/api/ai/chat-plan', {
        method: 'POST', headers,
        body: JSON.stringify({ message: userMsg, history: messages, existingTasks: tasks.filter(t => t.status === 'pending') })
      });
      if (!res.ok) throw new Error('Server error');
      const data = await res.json();
      const reply = data.reply || "I'm here to help!";
      setMessages(prev => [...prev, { role: 'assistant', text: reply }]);
      if (isProcessingVoice) speakText(reply);
      if (data.plan) setAiPlan(data.plan);
      if (data.newTasks?.length > 0) {
        for (const t of data.newTasks) {
          const r = await fetch('https://kairo-isfu.onrender.com/api/tasks', { method: 'POST', headers, body: JSON.stringify({ title: t.title, deadline: t.deadline }) });
          const task = await r.json();
          if (task.id) setTasks(prev => [...prev, task]);
        }
      }
    } catch {
      setMessages(prev => [...prev, { role: 'assistant', text: `Sorry, I ran into an issue. Please try again.` }]);
    }
    setChatLoading(false);
  }

  async function addTask() {
    if (!newTask.trim()) return;
    const res = await fetch('https://kairo-isfu.onrender.com/api/tasks', { method: 'POST', headers, body: JSON.stringify({ title: newTask, deadline }) });
    const task = await res.json();
    if (task.id) { setTasks(prev => [...prev, task]); addToast(`✓ "${newTask}" added`, 'success'); }
    setNewTask(''); setDeadline('');
  }

  async function completeTask(id) {
    await fetch(`https://kairo-isfu.onrender.com/api/tasks/${id}`, { method: 'PATCH', headers, body: JSON.stringify({ status: 'completed' }) });
    setTasks(prev => prev.map(t => t.id === id ? { ...t, status: 'completed' } : t));
    // Refresh weekly stats
    fetch('https://kairo-isfu.onrender.com/api/tasks/weekly-stats', { headers }).then(r => r.json()).then(data => { if (Array.isArray(data)) setWeeklyStats(data); });
    if (focusTask?.id === id) { setFocusTask(null); setTimerRunning(false); setTimer(0); }
    addToast('✓ Task completed! Great work 🎉', 'success');
  }

  async function deleteTask(id, title) {
    setDeletingId(id);
    await fetch(`https://kairo-isfu.onrender.com/api/tasks/${id}`, { method: 'DELETE', headers });
    setTasks(prev => prev.filter(t => t.id !== id));
    setDeletingId(null);
    addToast(`🗑 "${title}" deleted`, 'info');
  }
async function generateRecommendations() {
  setRecsLoading(true);
  try {
    const res = await fetch('https://kairo-isfu.onrender.com/api/ai/recommendations', {
      method: 'POST', headers,
      body: JSON.stringify({ tasks, weeklyStats, streak, user: { name: user.name } })
    });
    const data = await res.json();
    if (data.recommendations) { setRecommendations(data.recommendations); setRecsGenerated(true); }
  } catch (e) { addToast('Could not generate recommendations', 'urgent'); }
  setRecsLoading(false);
}

async function generateAutoPlan() {
  if (!autoInput.trim()) return;
  setAutoGoal(autoInput);
  setAutoInput('');
  setAutoLoading(true);
  try {
    const res = await fetch('https://kairo-isfu.onrender.com/api/ai/auto-plan', {
      method: 'POST', headers,
      body: JSON.stringify({ goal: autoInput, tasks, user: { name: user.name } })
    });
    const data = await res.json();
    if (data.steps) { setAutoSteps(data.steps); setAutoGenerated(true); }
  } catch (e) { addToast('Could not generate plan', 'urgent'); }
  setAutoLoading(false);
}

async function executeAutoStep(step) {
  const res = await fetch('https://kairo-isfu.onrender.com/api/tasks', {
    method: 'POST', headers,
    body: JSON.stringify({ title: step.task_title, deadline: step.deadline })
  });
  const task = await res.json();
  if (task.id) {
    setTasks(prev => [...prev, task]);
    addToast(`✓ "${step.task_title}" added to your list`, 'success');
    setAutoSteps(prev => prev.map(s => s === step ? { ...s, executed: true } : s));
  }
}

async function executeAllSteps() {
  for (const step of autoSteps.filter(s => !s.executed && s.action === 'create_task')) {
    await executeAutoStep(step);
  }
  addToast('✓ All tasks added!', 'success');
}

  function formatTime(s) {
    return `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`;
  }

  const pending = tasks.filter(t => t.status === 'pending');
  const done = tasks.filter(t => t.status === 'completed');
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });

  const cardData = [
    { icon: '🧠', label: 'AI Planning', title: 'Smart Day Planner', desc: 'Tell Kairo your tasks and get a prioritized schedule.', gradient: 'linear-gradient(135deg,#1a1040,#0a2030)', border: '#9B7FFF', accent: '#9B7FFF', stat: `${done.length} done today` },
    { icon: '⚡', label: 'Proactive', title: 'Never Miss a Deadline', desc: 'Kairo alerts you before things go wrong — not after.', gradient: 'linear-gradient(135deg,#0a2030,#001a20)', border: '#00CFFF', accent: '#00CFFF', stat: `${pending.length} tasks pending` },
    { icon: '🎯', label: 'Focus', title: 'Deep Work Mode', desc: 'Lock in on one task at a time with a built-in timer.', gradient: 'linear-gradient(135deg,#1a0828,#0d1030)', border: '#FF7FC0', accent: '#FF7FC0', stat: `${streak}d streak` },
  ];
  const recCardData = [
  { icon: '💡', label: 'Insights', title: 'Smart Patterns', desc: 'Kairo analyzes your habits to find patterns you might miss.', gradient: 'linear-gradient(135deg,#1a1040,#0a2030)', border: '#9B7FFF', accent: '#9B7FFF', stat: 'Personalized tips' },
  { icon: '📈', label: 'Growth', title: 'Productivity Boost', desc: 'Actionable recommendations to improve how you work every day.', gradient: 'linear-gradient(135deg,#0a2030,#001a20)', border: '#00CFFF', accent: '#00CFFF', stat: 'AI-powered' },
  { icon: '🏆', label: 'Optimize', title: 'Peak Performance', desc: 'Learn the best times and habits for your unique workflow.', gradient: 'linear-gradient(135deg,#1a0828,#0d1030)', border: '#FF7FC0', accent: '#FF7FC0', stat: 'Based on your data' },
];

const autoCardData = [
  { icon: '🤖', label: 'Autonomous', title: 'Auto Task Planner', desc: 'Tell Kairo your goal and it breaks it into an executable plan.', gradient: 'linear-gradient(135deg,#1a1040,#0a2030)', border: '#9B7FFF', accent: '#9B7FFF', stat: 'Zero manual work' },
  { icon: '⚙️', label: 'Execute', title: 'One-Click Execution', desc: 'Approve the plan and Kairo instantly creates all tasks.', gradient: 'linear-gradient(135deg,#0a2030,#001a20)', border: '#00CFFF', accent: '#00CFFF', stat: 'Instantly applied' },
  { icon: '🔮', label: 'Predict', title: 'Smart Scheduling', desc: 'Kairo predicts how long each step takes and fits it into your time.', gradient: 'linear-gradient(135deg,#1a0828,#0d1030)', border: '#FF7FC0', accent: '#FF7FC0', stat: 'Time-aware' },
];

const progressCardData = [
  { icon: '🔥', label: 'Streak', title: `${streak} Day Streak`, desc: streak >= 3 ? 'You\'re building real momentum.' : 'Complete tasks daily to build your streak.', gradient: 'linear-gradient(135deg,#2a1000,#1a0800)', border: '#FF6B35', accent: '#FF6B35', stat: streak >= 7 ? 'On fire!' : 'Keep going' },
  { icon: '📊', label: 'Weekly', title: `${totalThisWeek} Tasks Done`, desc: 'Your completion count for the last 7 days.', gradient: 'linear-gradient(135deg,#0a2030,#001a20)', border: '#00CFFF', accent: '#00CFFF', stat: 'This week' },
  { icon: '🏆', label: 'Best Day', title: bestDay.completed > 0 ? `${bestDay.completed} on ${bestDay.day}` : 'No data yet', desc: bestDay.completed > 0 ? `${bestDay.day} was your most productive day.` : 'Complete tasks to see your best day.', gradient: 'linear-gradient(135deg,#1a0828,#0d1030)', border: '#FF7FC0', accent: '#FF7FC0', stat: 'Personal best' },
];
  function PageHero({ badge, title, highlight, subtitle, actions, cards }) {
  return (
    <div style={{ position: 'relative', minHeight: '290px', background: '#000', borderBottom: '1px solid rgba(255,255,255,0.06)', overflow: 'hidden', padding: '2rem 2.5rem' }}>
      <FloatingPaths position={1} />
      <FloatingPaths position={-1} />
      <div style={{ position: 'relative', zIndex: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '2rem' }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', background: 'rgba(155,127,255,0.1)', border: '1px solid rgba(155,127,255,0.22)', borderRadius: '99px', padding: '4px 12px', fontSize: '0.7rem', color: '#9B7FFF', marginBottom: '0.9rem', letterSpacing: '0.06em', fontWeight: 500 }}>
              {badge}
            </div>
            <h1 style={{ fontSize: '2.1rem', fontWeight: 800, letterSpacing: '-1px', lineHeight: 1.1, marginBottom: '0.4rem' }}>
              {title}{' '}
              {highlight && <span style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{highlight}</span>}
            </h1>
            <p style={{ color: 'rgba(255,255,255,0.38)', fontSize: '0.85rem', marginBottom: '1.6rem' }}>{subtitle}</p>
          </motion.div>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.25 }} style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            {actions}
          </motion.div>
        </div>
        {cards && (
          <div style={{ width: '290px', height: '250px', flexShrink: 0, position: 'relative' }}>
            <CardSwap cardDistance={40} verticalDistance={50} delay={3500} pauseOnHover={true} width={268} height={160} skewAmount={4} easing="elastic">
              {cards.map((c, i) => (
                <Card key={i} style={{ background: c.gradient, border: `1px solid ${c.border}40`, borderRadius: '16px', padding: '1.2rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                    <div style={{ width: '28px', height: '28px', borderRadius: '7px', background: `${c.border}22`, border: `1px solid ${c.border}44`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.95rem' }}>{c.icon}</div>
                    <span style={{ fontSize: '0.65rem', color: c.accent, textTransform: 'uppercase', letterSpacing: '0.1em', fontWeight: 700 }}>{c.label}</span>
                  </div>
                  <div style={{ fontSize: '0.96rem', fontWeight: 700, color: 'white', marginBottom: '5px', lineHeight: 1.25 }}>{c.title}</div>
                  <p style={{ fontSize: '0.74rem', color: 'rgba(255,255,255,0.55)', lineHeight: 1.6, marginBottom: '8px' }}>{c.desc}</p>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '5px', fontSize: '0.68rem', color: c.accent, fontWeight: 600 }}>
                    <div style={{ width: '5px', height: '5px', borderRadius: '50%', background: c.accent }} />{c.stat}
                  </div>
                </Card>
              ))}
            </CardSwap>
          </div>
        )}
      </div>
    </div>
  );
}
  function NavBtn({ icon, label, page }) {
    const active = activePage === page;
    return (
      <button onClick={() => setActivePage(page)} style={{ display: 'flex', alignItems: 'center', gap: '9px', padding: '9px 10px', borderRadius: '8px', background: active ? 'rgba(155,127,255,0.12)' : 'transparent', border: 'none', color: active ? '#9B7FFF' : 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '0.85rem', fontWeight: active ? 600 : 400, width: '100%', textAlign: 'left', marginBottom: '2px', transition: 'all 0.15s' }}>
        <span>{icon}</span> {label}
        {active && <div style={{ marginLeft: 'auto', width: '4px', height: '4px', borderRadius: '50%', background: '#9B7FFF' }} />}
      </button>
    );
  }

  function VoiceBtn({ size = 'normal' }) {
    if (!voiceSupported) return null;
    const sm = size === 'small';
    return (
      <button onClick={toggleVoice}
        style={{ width: sm ? '34px' : '42px', height: sm ? '34px' : '42px', borderRadius: '50%', background: isListening ? 'rgba(239,68,68,0.2)' : 'rgba(155,127,255,0.1)', border: isListening ? '2px solid #f87171' : '1px solid rgba(155,127,255,0.35)', color: isListening ? '#f87171' : '#9B7FFF', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: sm ? '0.85rem' : '1rem', flexShrink: 0, animation: isListening ? 'voicePulse 1s infinite' : 'none' }}>
        {isListening ? '⏹' : '🎤'}
      </button>
    );
  }

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: '#080808', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', color: 'white' }}>
      <style>{`
        body{background:#080808!important;margin:0}*{box-sizing:border-box}
        input,textarea{color-scheme:dark}textarea{resize:none}
        ::-webkit-scrollbar{width:3px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.08);border-radius:2px}
        @keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
        @keyframes blink{0%,100%{opacity:1}50%{opacity:0.1}}
        @keyframes voicePulse{0%,100%{box-shadow:0 0 0 0 rgba(239,68,68,0.4)}50%{box-shadow:0 0 0 10px rgba(239,68,68,0)}}
        @keyframes timerPulse{0%,100%{opacity:1}50%{opacity:0.75}}
        @keyframes deleteShake{0%,100%{transform:translateX(0)}25%{transform:translateX(-4px)}75%{transform:translateX(4px)}}
        input::placeholder,textarea::placeholder{color:rgba(255,255,255,0.2)}
        .task-row{transition:background 0.15s,border-color 0.15s}.task-row:hover{background:rgba(255,255,255,0.05)!important}
        .del-btn{opacity:0;transition:opacity 0.15s}.task-row:hover .del-btn{opacity:1}
      `}</style>
{/* NOTIFICATION PANEL */}
<AnimatePresence>
  {showNotifPanel && (
    <>
      <div onClick={() => setShowNotifPanel(false)}
        style={{ position: 'fixed', inset: 0, zIndex: 998 }} />
      <motion.div
        initial={{ opacity: 0, y: -10, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: -10, scale: 0.97 }}
        style={{ position: 'fixed', top: '3.2rem', left: '10px', zIndex: 999, width: '320px', background: '#111', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '16px', boxShadow: '0 8px 40px rgba(0,0,0,0.7)', overflow: 'hidden' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem 1.2rem', borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
          <div>
            <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'white' }}>Notifications</div>
            <div style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.3)', marginTop: '1px' }}>{allNotifications.length} total</div>
          </div>
          <button
            onClick={() => { setAllNotifications(prev => prev.map(n => ({ ...n, read: true }))); setUnreadCount(0); }}
            style={{ fontSize: '0.72rem', color: '#9B7FFF', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 500 }}>
            Mark all read
          </button>
        </div>

        {/* List */}
        <div style={{ maxHeight: '380px', overflowY: 'auto' }}>
          {allNotifications.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '2.5rem 1rem', color: 'rgba(255,255,255,0.2)' }}>
              <div style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>🔔</div>
              <div style={{ fontSize: '0.85rem' }}>No notifications yet</div>
            </div>
          ) : allNotifications.map((n, i) => (
            <div key={n.id}
              onClick={() => {
                setAllNotifications(prev => prev.map((x, j) => j === i ? { ...x, read: true } : x));
                setUnreadCount(prev => Math.max(0, prev - (n.read ? 0 : 1)));
              }}
              style={{ display: 'flex', gap: '10px', padding: '12px 1.2rem', borderBottom: '1px solid rgba(255,255,255,0.05)', background: n.read ? 'transparent' : 'rgba(155,127,255,0.04)', cursor: 'pointer' }}>
              <div style={{ fontSize: '1rem', flexShrink: 0, marginTop: '1px' }}>
                {n.type === 'urgent' ? '🚨' : n.type === 'warning' ? '⏰' : n.type === 'success' ? '✅' : '🔔'}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: '0.82rem', color: 'rgba(255,255,255,0.85)', lineHeight: 1.5 }}>{n.msg}</div>
                <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.25)', marginTop: '3px' }}>
                  {n.time ? new Date(n.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''}
                </div>
              </div>
              {!n.read && (
                <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#9B7FFF', flexShrink: 0, marginTop: '5px' }} />
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        {allNotifications.length > 0 && (
          <div style={{ padding: '10px 1.2rem', borderTop: '1px solid rgba(255,255,255,0.07)' }}>
            <button
              onClick={() => { setAllNotifications([]); setUnreadCount(0); }}
              style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.3)', background: 'none', border: 'none', cursor: 'pointer' }}>
              Clear all
            </button>
          </div>
        )}
      </motion.div>
    </>
  )}
</AnimatePresence>
      {/* TOASTS */}
      <div style={{ position: 'fixed', top: '1.2rem', right: '1.2rem', zIndex: 9999, display: 'flex', flexDirection: 'column', gap: '8px', pointerEvents: 'none' }}>
        <AnimatePresence>
          {toasts.map(t => (
            <motion.div key={t.id} initial={{ opacity: 0, x: 60 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 60 }}
              style={{ pointerEvents: 'all', display: 'flex', alignItems: 'flex-start', gap: '10px', padding: '12px 16px', borderRadius: '12px', backdropFilter: 'blur(20px)', maxWidth: '320px', boxShadow: '0 4px 24px rgba(0,0,0,0.4)',
                background: t.type === 'urgent' ? 'rgba(239,68,68,0.18)' : t.type === 'warning' ? 'rgba(251,191,36,0.15)' : t.type === 'success' ? 'rgba(0,207,255,0.12)' : 'rgba(155,127,255,0.15)',
                border: `1px solid ${t.type === 'urgent' ? 'rgba(239,68,68,0.45)' : t.type === 'warning' ? 'rgba(251,191,36,0.35)' : t.type === 'success' ? 'rgba(0,207,255,0.35)' : 'rgba(155,127,255,0.35)'}`,
              }}>
              <div style={{ fontSize: '1rem', flexShrink: 0 }}>{t.type === 'urgent' ? '🚨' : t.type === 'warning' ? '⏰' : t.type === 'success' ? '✅' : '🔔'}</div>
              <div style={{ flex: 1, fontSize: '0.82rem', color: 'rgba(255,255,255,0.88)', lineHeight: 1.55 }}>{t.msg}</div>
              <button onClick={() => setToasts(p => p.filter(x => x.id !== t.id))} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.3)', cursor: 'pointer', fontSize: '1rem', lineHeight: 1, padding: 0 }}>×</button>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* SIDEBAR */}
      <div style={{ width: '220px', background: '#0a0a0a', borderRight: '1px solid rgba(255,255,255,0.06)', padding: '1.5rem 0.8rem', display: 'flex', flexDirection: 'column', flexShrink: 0, position: 'sticky', top: 0, height: '100vh' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 0.6rem 0.2rem' }}>
  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
    <KairoLogo />
    <span style={{ fontSize: '1rem', fontWeight: 700, letterSpacing: '0.15em', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>KAIRO</span>
  </div>
  <button
    onClick={() => { setShowNotifPanel(p => !p); setUnreadCount(0); }}
    style={{ position: 'relative', background: 'none', border: 'none', cursor: 'pointer', padding: '4px', color: 'rgba(255,255,255,0.5)', fontSize: '1rem', lineHeight: 1 }}
    title="Notifications">
    🔔
    {unreadCount > 0 && (
      <div style={{ position: 'absolute', top: '-2px', right: '-2px', width: '15px', height: '15px', borderRadius: '50%', background: '#ef4444', border: '2px solid #0a0a0a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.5rem', fontWeight: 700, color: 'white' }}>
        {unreadCount > 9 ? '9+' : unreadCount}
      </div>
    )}
  </button>
</div>
        <div style={{ fontSize: '0.62rem', color: 'rgba(255,255,255,0.18)', padding: '0 0.6rem 1.8rem' }}>Beyond Reminder. Into Action.</div>

        <div style={{ fontSize: '0.62rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(255,255,255,0.18)', padding: '0 0.6rem 0.4rem' }}>Workspace</div>
        <NavBtn icon="📋" label="My Tasks" page="tasks" />
        <NavBtn icon="✦" label="Plan with AI" page="plan" />
        <NavBtn icon="🎯" label="Focus Mode" page="focus" />

        <div style={{ fontSize: '0.62rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(255,255,255,0.18)', padding: '0.8rem 0.6rem 0.4rem' }}>Intelligence</div>
        <NavBtn icon="💡" label="Recommendations" page="recs" />
        <NavBtn icon="🤖" label="Auto Planner" page="auto" />
        <NavBtn icon="📊" label="My Progress" page="progress" />
        <div style={{ flex: 1 }} />

        {/* Streak in sidebar */}
        {streak > 0 && (
          <div style={{ margin: '0 0 0.8rem', padding: '8px 10px', background: 'rgba(155,127,255,0.08)', border: '1px solid rgba(155,127,255,0.15)', borderRadius: '10px' }}>
            <div style={{ fontSize: '0.7rem', color: '#9B7FFF', fontWeight: 600 }}>
              {streak >= 7 ? '🔥' : streak >= 3 ? '⚡' : '✨'} {streak} day streak
            </div>
            <div style={{ fontSize: '0.62rem', color: 'rgba(255,255,255,0.25)', marginTop: '2px' }}>Keep it going!</div>
          </div>
        )}

        {/* Progress bar */}
        <div style={{ padding: '0 0.2rem 1rem' }}>
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '10px', padding: '10px 12px' }}>
            <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.28)', marginBottom: '6px' }}>Today's progress</div>
            <div style={{ height: '4px', background: 'rgba(255,255,255,0.07)', borderRadius: '2px', overflow: 'hidden' }}>
              <div style={{ height: '100%', borderRadius: '2px', background: 'linear-gradient(90deg,#9B7FFF,#00CFFF)', width: tasks.length ? `${Math.round((done.length / tasks.length) * 100)}%` : '0%', transition: 'width 0.5s ease' }} />
            </div>
            <div style={{ fontSize: '0.65rem', color: 'rgba(255,255,255,0.22)', marginTop: '5px' }}>{done.length} of {tasks.length} done</div>
          </div>
        </div>

        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '9px', padding: '0 0.4rem 0.8rem' }}>
            <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.85rem', fontWeight: 700, flexShrink: 0 }}>
              {user.name[0].toUpperCase()}
            </div>
            <div style={{ minWidth: 0 }}>
              <div style={{ fontSize: '0.82rem', fontWeight: 600, color: 'white', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user.name}</div>
              <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.28)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user.email}</div>
            </div>
          </div>
          <button onClick={onLogout} style={{ width: '100%', padding: '8px', background: 'transparent', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '7px', color: 'rgba(255,255,255,0.3)', cursor: 'pointer', fontSize: '0.78rem' }}
            onMouseEnter={e => { e.target.style.borderColor = 'rgba(255,255,255,0.18)'; e.target.style.color = 'rgba(255,255,255,0.6)'; }}
            onMouseLeave={e => { e.target.style.borderColor = 'rgba(255,255,255,0.08)'; e.target.style.color = 'rgba(255,255,255,0.3)'; }}>
            Log out
          </button>
        </div>
      </div>

      {/* MAIN */}
      <div style={{ flex: 1, overflowY: 'auto', height: '100vh' }}>

        {/* ════ TASKS PAGE ════ */}
        {activePage === 'tasks' && (
          <div>
            <PageHero
  badge="✦ AI Productivity"
  title="Good day,"
  highlight={`${user.name} 👋`}
  subtitle={`${today} · ${pending.length} task${pending.length !== 1 ? 's' : ''} remaining`}
  cards={cardData}
  actions={<>
    <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '9px', padding: '1.5px' }}>
      <button onClick={() => setActivePage('plan')} style={{ padding: '9px 20px', background: 'rgba(5,5,15,0.92)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer' }}>✦ Plan with AI</button>
    </div>
    <button onClick={() => setActivePage('recs')} style={{ padding: '9px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '9px', color: 'rgba(255,255,255,0.65)', fontSize: '0.85rem', cursor: 'pointer' }}>💡 Get tips</button>
    <button onClick={() => setActivePage('auto')} style={{ padding: '9px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '9px', color: 'rgba(255,255,255,0.65)', fontSize: '0.85rem', cursor: 'pointer' }}>🤖 Auto Plan</button>
  </>}
/>
            {/* TASKS BODY */}
            <div style={{ padding: '1.8rem 2.5rem' }}>
              {/* Add task */}
              <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '16px', padding: '1.4rem 1.6rem', marginBottom: '1.6rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '1rem' }}>
                  <div style={{ width: '4px', height: '18px', borderRadius: '3px', background: 'linear-gradient(180deg,#9B7FFF,#00CFFF)' }} />
                  <span style={{ fontSize: '0.74rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.35)' }}>Add New Task</span>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr auto auto', gap: '10px', alignItems: 'end' }}>
                  <div>
                    <label style={{ display: 'block', fontSize: '0.71rem', color: 'rgba(255,255,255,0.35)', marginBottom: '6px', fontWeight: 500 }}>Task name</label>
                    <input type="text" value={newTask} onChange={e => setNewTask(e.target.value)}
                      placeholder="What do you need to accomplish?"
                      onKeyDown={e => e.key === 'Enter' && addTask()}
                      style={{ width: '100%', padding: '10px 14px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '10px', color: 'white', fontSize: '0.9rem', outline: 'none', transition: 'border-color 0.2s' }}
                      onFocus={e => e.target.style.borderColor = 'rgba(155,127,255,0.55)'}
                      onBlur={e => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
                    />
                  </div>
                  <div>
                    <label style={{ display: 'block', fontSize: '0.71rem', color: 'rgba(255,255,255,0.35)', marginBottom: '6px', fontWeight: 500 }}>Deadline</label>
                    <input type="datetime-local" value={deadline} onChange={e => setDeadline(e.target.value)}
                      style={{ padding: '10px 12px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '10px', color: 'rgba(255,255,255,0.65)', fontSize: '0.85rem', outline: 'none' }}
                      onFocus={e => e.target.style.borderColor = 'rgba(155,127,255,0.55)'}
                      onBlur={e => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
                    />
                  </div>
                  <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '10px', padding: '1.5px' }}>
                    <button onClick={addTask} style={{ padding: '10px 20px', background: 'rgba(5,5,15,0.9)', border: 'none', borderRadius: '9px', color: 'white', fontSize: '0.88rem', fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' }}>Add →</button>
                  </div>
                </div>
              </motion.div>

              {/* Pending */}
              <div style={{ marginBottom: '1.6rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '0.8rem' }}>
                  <span style={{ fontSize: '0.71rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.3)' }}>Pending</span>
                  <div style={{ background: 'rgba(155,127,255,0.15)', border: '1px solid rgba(155,127,255,0.3)', borderRadius: '99px', padding: '1px 8px', fontSize: '0.67rem', color: '#9B7FFF', fontWeight: 600 }}>{pending.length}</div>
                  <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.05)' }} />
                </div>
                {pending.length === 0 ? (
                  <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px dashed rgba(255,255,255,0.08)', borderRadius: '14px', textAlign: 'center', padding: '2.5rem', color: 'rgba(255,255,255,0.18)', fontSize: '0.88rem' }}>
                    No pending tasks — <span style={{ color: '#9B7FFF', cursor: 'pointer', fontWeight: 500 }} onClick={() => setActivePage('plan')}>chat with Kairo AI ✦</span>
                  </div>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                    <AnimatePresence>
                      {pending.map((task, idx) => {
                        const isOverdue = task.deadline && new Date(task.deadline) < new Date();
                        const minsLeft = task.deadline ? Math.round((new Date(task.deadline) - new Date()) / 60000) : null;
                        const isUrgent = minsLeft !== null && minsLeft > 0 && minsLeft <= 60;
                        const isDeleting = deletingId === task.id;
                        return (
                          <motion.div key={task.id} className="task-row"
                            initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -30, height: 0 }} transition={{ delay: idx * 0.03 }}
                            style={{ display: 'flex', alignItems: 'center', gap: '11px', background: 'rgba(255,255,255,0.03)', border: `1px solid ${isOverdue ? 'rgba(239,68,68,0.3)' : isUrgent ? 'rgba(251,191,36,0.22)' : 'rgba(255,255,255,0.07)'}`, borderRadius: '12px', padding: '12px 14px', animation: isDeleting ? 'deleteShake 0.3s ease' : 'none' }}>
                            <div style={{ width: '8px', height: '8px', borderRadius: '50%', flexShrink: 0, background: isOverdue ? '#ef4444' : isUrgent ? '#fbbf24' : 'rgba(155,127,255,0.7)' }} />
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ fontSize: '0.88rem', fontWeight: 500, color: 'white', marginBottom: '2px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{task.title}</div>
                              {task.deadline && (
                                <div style={{ fontSize: '0.71rem', color: isOverdue ? '#f87171' : isUrgent ? '#fbbf24' : 'rgba(255,255,255,0.3)' }}>
                                  {isOverdue ? '⚠ Overdue · ' : isUrgent ? '⏰ ' : '📅 '}{new Date(task.deadline).toLocaleString()}
                                  {isUrgent && !isOverdue && <span style={{ fontWeight: 600 }}> · {minsLeft}m left</span>}
                                </div>
                              )}
                            </div>
                            <button onClick={() => { setFocusTask(task); setActivePage('focus'); setTimer(0); setTimerRunning(false); }}
                              style={{ padding: '5px 11px', background: 'rgba(155,127,255,0.08)', border: '1px solid rgba(155,127,255,0.22)', borderRadius: '6px', color: '#9B7FFF', fontSize: '0.71rem', cursor: 'pointer', fontWeight: 500, flexShrink: 0 }}>Focus</button>
                            <button onClick={() => completeTask(task.id)}
                              style={{ padding: '5px 12px', background: 'rgba(0,207,255,0.06)', border: '1px solid rgba(0,207,255,0.18)', borderRadius: '6px', color: '#00CFFF', fontSize: '0.71rem', cursor: 'pointer', flexShrink: 0 }}>✓ Done</button>
                            <button className="del-btn" onClick={() => deleteTask(task.id, task.title)}
                              title="Delete task"
                              style={{ padding: '5px 9px', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.18)', borderRadius: '6px', color: '#f87171', fontSize: '0.78rem', cursor: 'pointer', flexShrink: 0 }}>🗑</button>
                          </motion.div>
                        );
                      })}
                    </AnimatePresence>
                  </div>
                )}
              </div>

              {/* Completed */}
              {done.length > 0 && (
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '0.8rem' }}>
                    <span style={{ fontSize: '0.71rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.3)' }}>Completed</span>
                    <div style={{ background: 'rgba(0,207,255,0.1)', border: '1px solid rgba(0,207,255,0.25)', borderRadius: '99px', padding: '1px 8px', fontSize: '0.67rem', color: '#00CFFF', fontWeight: 600 }}>{done.length}</div>
                    <div style={{ flex: 1, height: '1px', background: 'rgba(255,255,255,0.05)' }} />
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
                    <AnimatePresence>
                      {done.map(task => (
                        <motion.div key={task.id} className="task-row"
                          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, height: 0 }}
                          style={{ display: 'flex', alignItems: 'center', gap: '10px', background: 'rgba(255,255,255,0.015)', border: '1px solid rgba(255,255,255,0.04)', borderRadius: '10px', padding: '10px 14px', opacity: 0.5 }}>
                          <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#00CFFF', flexShrink: 0 }} />
                          <span style={{ fontSize: '0.85rem', textDecoration: 'line-through', color: 'rgba(255,255,255,0.4)', flex: 1 }}>{task.title}</span>
                          <span style={{ fontSize: '0.67rem', color: 'rgba(0,207,255,0.6)', fontWeight: 500 }}>✓</span>
                          <button className="del-btn" onClick={() => deleteTask(task.id, task.title)}
                            style={{ padding: '4px 8px', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.15)', borderRadius: '6px', color: '#f87171', fontSize: '0.73rem', cursor: 'pointer' }}>🗑</button>
                        </motion.div>
                      ))}
                    </AnimatePresence>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ════ PROGRESS PAGE ════ */}
        {activePage === 'progress' && (
  <div>
    <PageHero
      badge="📊 Weekly Progress"
      title="Your"
      highlight="Consistency"
      subtitle="Track how you're building momentum over time"
      cards={progressCardData}
      actions={<>
        <button onClick={() => setActivePage('tasks')} style={{ padding: '9px 18px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '9px', color: 'rgba(255,255,255,0.65)', fontSize: '0.85rem', cursor: 'pointer' }}>📋 Add tasks</button>
        <button onClick={() => setActivePage('recs')} style={{ padding: '9px 18px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '9px', color: 'rgba(255,255,255,0.65)', fontSize: '0.85rem', cursor: 'pointer' }}>💡 Get tips</button>
      </>}
    />
    <div style={{ padding: '1.8rem 2.5rem' }}>
            

            {/* Streak + summary cards */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '1rem', marginBottom: '2rem' }}>
              {[
                { icon: streak >= 7 ? '🔥' : streak >= 3 ? '⚡' : '✨', val: `${streak}d`, label: 'Current streak', color: streak >= 7 ? '#FF6B35' : '#9B7FFF', sub: streak >= 7 ? 'You\'re on fire!' : streak >= 3 ? 'Building momentum' : 'Keep going!' },
                { icon: '✅', val: totalThisWeek, label: 'Done this week', color: '#00CFFF', sub: 'tasks completed' },
                { icon: '🏆', val: bestDay.completed > 0 ? `${bestDay.completed}` : '—', label: 'Best day', color: '#FF7FC0', sub: bestDay.completed > 0 ? `${bestDay.day} was your best` : 'Complete tasks to track' },
                { icon: '📋', val: tasks.length, label: 'Total tasks', color: 'rgba(255,255,255,0.6)', sub: `${done.length} completed` },
              ].map((s, i) => (
                <motion.div key={s.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}
                  style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '16px', padding: '1.4rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
                    <div style={{ width: '38px', height: '38px', borderRadius: '10px', background: `${s.color}14`, border: `1px solid ${s.color}28`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem' }}>{s.icon}</div>
                  </div>
                  <div style={{ fontSize: '2rem', fontWeight: 800, color: s.color, lineHeight: 1, marginBottom: '4px' }}>{s.val}</div>
                  <div style={{ fontSize: '0.75rem', fontWeight: 600, color: 'rgba(255,255,255,0.55)', marginBottom: '2px' }}>{s.label}</div>
                  <div style={{ fontSize: '0.68rem', color: 'rgba(255,255,255,0.25)' }}>{s.sub}</div>
                </motion.div>
              ))}
            </div>

            {/* Weekly bar chart */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
              style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '16px', padding: '1.6rem', marginBottom: '1.5rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.2rem' }}>
                <div>
                  <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'white', marginBottom: '2px' }}>Tasks completed — last 7 days</div>
                  <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.3)' }}>Each bar = tasks finished that day</div>
                </div>
                <div style={{ fontSize: '0.72rem', color: '#9B7FFF', background: 'rgba(155,127,255,0.1)', border: '1px solid rgba(155,127,255,0.2)', padding: '4px 10px', borderRadius: '99px', fontWeight: 600 }}>
                  {totalThisWeek} total
                </div>
              </div>
              {weeklyStats.length > 0 ? <WeeklyChart data={weeklyStats} /> : (
                <div style={{ textAlign: 'center', padding: '2rem', color: 'rgba(255,255,255,0.2)', fontSize: '0.85rem' }}>Complete tasks to see your chart</div>
              )}
            </motion.div>

            {/* Streak calendar dots */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
              style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '16px', padding: '1.6rem', marginBottom: '1.5rem' }}>
              <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'white', marginBottom: '0.4rem' }}>Activity this week</div>
              <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.3)', marginBottom: '1.2rem' }}>Filled = you completed at least one task</div>
              <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                {weeklyStats.map((d, i) => {
                  const isToday = i === weeklyStats.length - 1;
                  const active = d.completed > 0;
                  return (
                    <div key={d.date} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '5px' }}>
                      <div style={{ width: '36px', height: '36px', borderRadius: '10px', background: active ? 'linear-gradient(135deg,#9B7FFF,#00CFFF)' : 'rgba(255,255,255,0.05)', border: `1px solid ${isToday ? 'rgba(155,127,255,0.5)' : active ? 'transparent' : 'rgba(255,255,255,0.07)'}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: active ? '1rem' : '0.7rem', color: active ? 'white' : 'rgba(255,255,255,0.15)' }}>
                        {active ? (d.completed > 5 ? '🔥' : d.completed > 2 ? '⚡' : '✓') : '·'}
                      </div>
                      <div style={{ fontSize: '0.62rem', color: isToday ? '#9B7FFF' : 'rgba(255,255,255,0.28)', fontWeight: isToday ? 700 : 400 }}>{isToday ? 'Today' : d.day}</div>
                    </div>
                  );
                })}
              </div>
            </motion.div>

            {/* Motivational message */}
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
              style={{ background: streak >= 3 ? 'rgba(155,127,255,0.08)' : 'rgba(255,255,255,0.025)', border: `1px solid ${streak >= 3 ? 'rgba(155,127,255,0.2)' : 'rgba(255,255,255,0.07)'}`, borderRadius: '16px', padding: '1.4rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <div style={{ fontSize: '2.5rem' }}>{streak >= 7 ? '🔥' : streak >= 3 ? '⚡' : streak >= 1 ? '✨' : '💪'}</div>
              <div>
                <div style={{ fontSize: '0.95rem', fontWeight: 700, color: 'white', marginBottom: '4px' }}>
                  {streak >= 7 ? `${streak} days strong — you're unstoppable, ${user.name.split(' ')[0]}!`
                    : streak >= 3 ? `${streak} day streak — ${user.name.split(' ')[0]}, you're building real momentum!`
                    : streak >= 1 ? `Great start, ${user.name.split(' ')[0]}! Keep completing tasks daily.`
                    : `Start your streak today, ${user.name.split(' ')[0]}!`}
                </div>
                <div style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.4)', lineHeight: 1.6 }}>
                  {streak >= 7 ? 'You\'ve been consistently productive for over a week. That\'s rare — keep it up!'
                    : streak >= 3 ? `${7 - streak} more days and you'll hit a full week streak. You've got this!`
                    : streak >= 1 ? 'Consistency is the key. Come back tomorrow to grow your streak!'
                    : 'Complete at least one task today to start your streak. Small steps count!'}
                </div>
              </div>
            </motion.div>
          </div>
        </div>
        )}

        {/* ════ PLAN WITH AI PAGE ════ */}
        {activePage === 'plan' && (
          <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', padding: '2rem 2.5rem', position: 'relative' }}>
            <div style={{ position: 'fixed', bottom: 0, left: '220px', right: 0, height: '55vh', pointerEvents: 'none', zIndex: 0, overflow: 'hidden' }}>
              <div style={{ position: 'absolute', bottom: '-55%', left: '50%', transform: 'translateX(-50%)', width: '130%', paddingBottom: '45%', borderRadius: '50%', background: 'radial-gradient(ellipse at center, rgba(100,80,255,0.1) 0%, rgba(0,150,255,0.05) 40%, transparent 70%)', border: '1px solid rgba(100,120,255,0.07)' }} />
            </div>

            {isListening && (
              <div style={{ position: 'fixed', top: '1.5rem', left: '50%', transform: 'translateX(-50%)', zIndex: 100, display: 'flex', alignItems: 'center', gap: '10px', background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.35)', borderRadius: '99px', padding: '8px 20px', backdropFilter: 'blur(12px)' }}>
                <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#f87171', animation: 'voicePulse 1s infinite' }} />
                <span style={{ fontSize: '0.85rem', color: '#fca5a5', fontWeight: 500 }}>Listening... speak now</span>
              </div>
            )}

            {messages.length <= 1 ? (
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', position: 'relative', zIndex: 1 }}>
                <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '99px', padding: '6px 16px', fontSize: '0.75rem', color: 'rgba(255,255,255,0.45)', marginBottom: '1.5rem' }}>
                    ✦ AI-Powered Planning
                  </div>
                  <h1 style={{ fontSize: '2.8rem', fontWeight: 800, letterSpacing: '-1.5px', lineHeight: 1.1, marginBottom: '0.8rem' }}>
                    What will you{' '}
                    <span style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', fontStyle: 'italic' }}>accomplish</span>
                    {' '}today?
                  </h1>
                  <p style={{ color: 'rgba(255,255,255,0.35)', fontSize: '0.95rem' }}>Type or speak — Kairo builds your smart action plan instantly.</p>
                </div>

                <div style={{ width: '100%', maxWidth: '680px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '18px', padding: '1.1rem 1.1rem 0.85rem', backdropFilter: 'blur(20px)', boxShadow: '0 0 60px rgba(100,80,255,0.07)' }}>
                  <textarea value={chatInput} onChange={e => setChatInput(e.target.value)}
                    onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSendMessage(); } }}
                    placeholder="e.g. I have a report due at 3pm, a meeting at 4pm, and need to reply to emails..."
                    rows={3} style={{ width: '100%', background: 'transparent', border: 'none', color: 'white', fontSize: '0.95rem', outline: 'none', fontFamily: 'inherit', lineHeight: 1.7, padding: '0.2rem 0.4rem' }}
                  />
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: '0.7rem', borderTop: '1px solid rgba(255,255,255,0.07)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <VoiceBtn />
                      {voiceSupported && <span style={{ fontSize: '0.7rem', color: 'rgba(255,255,255,0.22)' }}>or speak</span>}
                    </div>
                    <button onClick={() => handleSendMessage()} disabled={chatLoading || !chatInput.trim()}
                      style={{ padding: '9px 22px', background: chatInput.trim() ? 'linear-gradient(135deg,#9B7FFF,#00CFFF)' : 'rgba(255,255,255,0.07)', border: 'none', borderRadius: '9px', color: chatInput.trim() ? 'white' : 'rgba(255,255,255,0.25)', fontSize: '0.88rem', fontWeight: 600, cursor: chatInput.trim() ? 'pointer' : 'not-allowed' }}>
                      Plan now ▶
                    </button>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '8px', marginTop: '1.2rem', flexWrap: 'wrap', justifyContent: 'center' }}>
                  {['📋 I have 5 tasks due today', '⚡ Report at 3pm, meeting at 4pm', '🎯 Help me prioritize', '😩 I\'m overwhelmed'].map(ex => (
                    <button key={ex} onClick={() => setChatInput(ex.replace(/^.{2}/, '').trim())}
                      style={{ padding: '7px 14px', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '10px', color: 'rgba(255,255,255,0.38)', fontSize: '0.8rem', cursor: 'pointer' }}>
                      {ex}
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div style={{ flex: 1, display: 'flex', gap: '1.5rem', position: 'relative', zIndex: 1, minHeight: 0 }}>
                <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
                  <div style={{ marginBottom: '1rem' }}>
                    <h1 style={{ fontSize: '1.3rem', fontWeight: 800, letterSpacing: '-0.5px' }}>✦ Plan with Kairo AI</h1>
                    <p style={{ color: 'rgba(255,255,255,0.28)', fontSize: '0.78rem', marginTop: '2px' }}>Type or speak your thoughts</p>
                  </div>
                  <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '10px', paddingBottom: '1rem', paddingRight: '4px' }}>
                    {messages.map((msg, i) => (
                      <div key={i} style={{ display: 'flex', justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start', animation: 'fadeUp 0.25s ease' }}>
                        {msg.role === 'assistant' && (
                          <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginRight: '8px', marginTop: '2px' }}><KairoLogo /></div>
                        )}
                        <div style={{ maxWidth: '75%', padding: '10px 14px', borderRadius: msg.role === 'user' ? '14px 14px 4px 14px' : '4px 14px 14px 14px', background: msg.role === 'user' ? 'linear-gradient(135deg,#9B7FFF,#00CFFF)' : 'rgba(255,255,255,0.05)', border: msg.role === 'user' ? 'none' : '1px solid rgba(255,255,255,0.07)', fontSize: '0.87rem', lineHeight: 1.7, color: 'white', whiteSpace: 'pre-wrap' }}>
                          {msg.text}
                          {msg.role === 'assistant' && (
                            <div style={{ display: 'flex', gap: '8px', marginTop: '5px' }}>
                              <button onClick={() => speakText(msg.text)} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.28)', fontSize: '0.7rem', cursor: 'pointer', padding: 0 }}>🔊 Read aloud</button>
                              <button onClick={stopSpeaking} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.18)', fontSize: '0.7rem', cursor: 'pointer', padding: 0 }}>⏹ Stop</button>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    {chatLoading && (
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}><KairoLogo /></div>
                        <div style={{ padding: '10px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '14px', display: 'flex', gap: '5px', alignItems: 'center' }}>
                          {[0, 1, 2].map(d => <div key={d} style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#9B7FFF', animation: `blink 1.2s ${d * 0.2}s infinite` }} />)}
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>
                  <div style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.09)', borderRadius: '14px', padding: '0.8rem 1rem 0.6rem' }}>
                    <textarea value={chatInput} onChange={e => setChatInput(e.target.value)}
                      onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSendMessage(); } }}
                      placeholder="Reply to Kairo... (Enter to send)" rows={2}
                      style={{ width: '100%', background: 'transparent', border: 'none', color: 'white', fontSize: '0.9rem', outline: 'none', fontFamily: 'inherit', lineHeight: 1.6 }}
                    />
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: '0.5rem', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <VoiceBtn size="small" />
                        <button onClick={() => { setMessages([{ role: 'assistant', text: `Hey ${user.name}! 👋 What do you need to get done today?` }]); setAiPlan(null); setChatInput(''); }}
                          style={{ fontSize: '0.73rem', color: 'rgba(255,255,255,0.22)', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>↺ Start over</button>
                      </div>
                      <button onClick={() => handleSendMessage()} disabled={chatLoading || !chatInput.trim()}
                        style={{ padding: '7px 16px', background: chatInput.trim() ? 'linear-gradient(135deg,#9B7FFF,#00CFFF)' : 'rgba(255,255,255,0.07)', border: 'none', borderRadius: '8px', color: chatInput.trim() ? 'white' : 'rgba(255,255,255,0.25)', fontSize: '0.84rem', fontWeight: 600, cursor: chatInput.trim() ? 'pointer' : 'not-allowed' }}>
                        Send ▶
                      </button>
                    </div>
                  </div>
                </div>

                {aiPlan && (
                  <div style={{ width: '265px', flexShrink: 0, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '7px' }}>
                    <div style={{ fontSize: '0.68rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(255,255,255,0.22)', marginBottom: '4px' }}>✦ Today's Plan</div>
                    {aiPlan.map((item, i) => (
                      <div key={i} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '10px', padding: '11px 13px', animation: 'fadeUp 0.3s ease' }}>
                        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '4px' }}>
                          <div style={{ width: '20px', height: '20px', borderRadius: '50%', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.63rem', fontWeight: 700, flexShrink: 0, marginTop: '1px' }}>{i + 1}</div>
                          <span style={{ fontSize: '0.84rem', fontWeight: 600, color: 'white', lineHeight: 1.3 }}>{item.title}</span>
                        </div>
                        {item.time_block && <div style={{ fontSize: '0.7rem', color: '#9B7FFF', marginBottom: '3px', paddingLeft: '28px' }}>⏰ {item.time_block}</div>}
                        {item.reason && <div style={{ fontSize: '0.73rem', color: 'rgba(255,255,255,0.32)', lineHeight: 1.5, paddingLeft: '28px' }}>{item.reason}</div>}
                        {item.at_risk && <div style={{ fontSize: '0.68rem', color: '#f87171', marginTop: '3px', paddingLeft: '28px' }}>⚠ At risk</div>}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
{/* ════ RECOMMENDATIONS ════ */}
{activePage === 'recs' && (
  <div>
    <PageHero
      badge="💡 AI Intelligence"
      title="Personalized"
      highlight="Recommendations"
      subtitle="Kairo analyzes your patterns to help you work smarter"
      cards={recCardData}
      actions={<>
        <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '9px', padding: '1.5px' }}>
          <button onClick={generateRecommendations} disabled={recsLoading}
            style={{ padding: '9px 20px', background: 'rgba(5,5,15,0.92)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '0.85rem', fontWeight: 600, cursor: recsLoading ? 'not-allowed' : 'pointer' }}>
            {recsLoading ? '⟳ Analyzing...' : '💡 Get my recommendations'}
          </button>
        </div>
        {recsGenerated && <button onClick={() => { setRecommendations([]); setRecsGenerated(false); }} style={{ padding: '9px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '9px', color: 'rgba(255,255,255,0.5)', fontSize: '0.85rem', cursor: 'pointer' }}>↺ Refresh</button>}
      </>}
    />
    <div style={{ padding: '1.8rem 2.5rem' }}>
      {!recsGenerated && !recsLoading && (
        <div style={{ background: 'rgba(155,127,255,0.04)', border: '1px dashed rgba(155,127,255,0.2)', borderRadius: '16px', padding: '3rem', textAlign: 'center' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>💡</div>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem' }}>Get your personalized productivity tips</h3>
          <p style={{ color: 'rgba(255,255,255,0.35)', fontSize: '0.88rem', marginBottom: '1.5rem', maxWidth: '400px', margin: '0 auto 1.5rem' }}>Kairo will analyze your tasks, completion patterns, and work habits to give you actionable recommendations.</p>
          <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '9px', padding: '1.5px', display: 'inline-block' }}>
            <button onClick={generateRecommendations} style={{ padding: '10px 24px', background: 'rgba(5,5,15,0.9)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '0.9rem', fontWeight: 600, cursor: 'pointer' }}>✦ Analyze my productivity</button>
          </div>
        </div>
      )}
      {recsLoading && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {[1,2,3,4].map(i => (
            <div key={i} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '14px', padding: '1.4rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(155,127,255,0.08)', animation: 'blink 1.5s infinite' }} />
                <div style={{ flex: 1 }}>
                  <div style={{ height: '12px', background: 'rgba(255,255,255,0.05)', borderRadius: '6px', marginBottom: '8px', width: '60%', animation: 'blink 1.5s infinite' }} />
                  <div style={{ height: '10px', background: 'rgba(255,255,255,0.03)', borderRadius: '6px', width: '80%', animation: 'blink 1.5s 0.2s infinite' }} />
                </div>
              </div>
            </div>
          ))}
          <p style={{ textAlign: 'center', color: 'rgba(255,255,255,0.3)', fontSize: '0.82rem' }}>Kairo is analyzing your productivity patterns...</p>
        </div>
      )}
      {recsGenerated && recommendations.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {recommendations.map((rec, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}
              style={{ background: 'rgba(255,255,255,0.03)', border: `1px solid ${rec.priority === 'high' ? 'rgba(155,127,255,0.25)' : 'rgba(255,255,255,0.07)'}`, borderRadius: '14px', padding: '1.4rem' }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                <div style={{ width: '42px', height: '42px', borderRadius: '11px', background: 'rgba(155,127,255,0.1)', border: '1px solid rgba(155,127,255,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.3rem', flexShrink: 0 }}>{rec.icon || '💡'}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '5px', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '0.92rem', fontWeight: 700, color: 'white' }}>{rec.title}</span>
                    {rec.priority === 'high' && <span style={{ fontSize: '0.65rem', background: 'rgba(155,127,255,0.15)', color: '#9B7FFF', border: '1px solid rgba(155,127,255,0.3)', padding: '2px 8px', borderRadius: '99px', fontWeight: 600 }}>High impact</span>}
                    {rec.category && <span style={{ fontSize: '0.65rem', background: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.35)', padding: '2px 8px', borderRadius: '99px' }}>{rec.category}</span>}
                  </div>
                  <p style={{ fontSize: '0.84rem', color: 'rgba(255,255,255,0.55)', lineHeight: 1.65, marginBottom: rec.action ? '0.8rem' : 0 }}>{rec.description}</p>
                  {rec.action && (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 12px', background: 'rgba(155,127,255,0.06)', border: '1px solid rgba(155,127,255,0.15)', borderRadius: '8px', fontSize: '0.78rem', color: '#9B7FFF' }}>
                      <span>→</span><span style={{ fontWeight: 500 }}>Action: {rec.action}</span>
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  </div>
)}

{/* ════ AUTO PLANNER ════ */}
{activePage === 'auto' && (
  <div>
    <PageHero
      badge="🤖 Autonomous AI"
      title="Auto Task"
      highlight="Planner"
      subtitle="Tell Kairo your goal — it breaks it down and executes automatically"
      cards={autoCardData}
      actions={<>
        <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '9px', padding: '1.5px' }}>
          <button onClick={() => { setAutoSteps([]); setAutoGenerated(false); setAutoGoal(''); setAutoInput(''); }} style={{ padding: '9px 20px', background: 'rgba(5,5,15,0.92)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer' }}>🤖 New plan</button>
        </div>
        {autoGenerated && <button onClick={executeAllSteps} style={{ padding: '9px 16px', background: 'rgba(0,207,255,0.1)', border: '1px solid rgba(0,207,255,0.25)', borderRadius: '9px', color: '#00CFFF', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer' }}>⚡ Add all to tasks</button>}
      </>}
    />
    <div style={{ padding: '1.8rem 2.5rem' }}>
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
        style={{ background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '16px', padding: '1.4rem 1.6rem', marginBottom: '1.6rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '1rem' }}>
          <div style={{ width: '4px', height: '18px', borderRadius: '3px', background: 'linear-gradient(180deg,#9B7FFF,#00CFFF)' }} />
          <span style={{ fontSize: '0.74rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.35)' }}>Describe your goal</span>
        </div>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-end' }}>
          <input type="text" value={autoInput} onChange={e => setAutoInput(e.target.value)}
            placeholder="e.g. Prepare a presentation for client meeting on Friday"
            onKeyDown={e => e.key === 'Enter' && generateAutoPlan()}
            style={{ flex: 1, padding: '12px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '10px', color: 'white', fontSize: '0.92rem', outline: 'none' }}
            onFocus={e => e.target.style.borderColor = 'rgba(155,127,255,0.55)'}
            onBlur={e => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
          />
          <div style={{ background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', borderRadius: '10px', padding: '1.5px' }}>
            <button onClick={generateAutoPlan} disabled={autoLoading || !autoInput.trim()}
              style={{ padding: '12px 22px', background: 'rgba(5,5,15,0.9)', border: 'none', borderRadius: '9px', color: 'white', fontSize: '0.88rem', fontWeight: 700, cursor: autoLoading || !autoInput.trim() ? 'not-allowed' : 'pointer', whiteSpace: 'nowrap' }}>
              {autoLoading ? '⟳ Planning...' : '🤖 Auto Plan →'}
            </button>
          </div>
        </div>
        <div style={{ display: 'flex', gap: '6px', marginTop: '10px', flexWrap: 'wrap' }}>
          {['Launch a product feature', 'Prepare for job interview', 'Complete a research project', 'Organize team event'].map(eg => (
            <button key={eg} onClick={() => setAutoInput(eg)} style={{ padding: '5px 12px', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '99px', color: 'rgba(255,255,255,0.35)', fontSize: '0.75rem', cursor: 'pointer' }}>{eg}</button>
          ))}
        </div>
      </motion.div>

      {autoLoading && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          <p style={{ fontSize: '0.82rem', color: 'rgba(255,255,255,0.3)', marginBottom: '4px' }}>🤖 Building execution plan for: <strong style={{ color: '#9B7FFF' }}>{autoGoal}</strong></p>
          {[1,2,3,4,5].map(i => (
            <div key={i} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '12px', padding: '1rem 1.2rem', display: 'flex', alignItems: 'center', gap: '12px' }}>
              <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: 'rgba(155,127,255,0.08)', animation: 'blink 1.5s infinite', flexShrink: 0 }} />
              <div style={{ height: '11px', background: 'rgba(255,255,255,0.05)', borderRadius: '5px', flex: 1, animation: `blink 1.5s ${i*0.1}s infinite` }} />
            </div>
          ))}
        </div>
      )}

      {autoGenerated && autoSteps.length > 0 && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem', flexWrap: 'wrap', gap: '10px' }}>
            <div>
              <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '2px' }}>🤖 Plan: <span style={{ color: '#9B7FFF' }}>{autoGoal}</span></h3>
              <p style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.3)' }}>{autoSteps.length} steps · Add individually or all at once</p>
            </div>
            <button onClick={executeAllSteps} style={{ padding: '9px 18px', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', border: 'none', borderRadius: '8px', color: 'white', fontSize: '0.82rem', fontWeight: 600, cursor: 'pointer' }}>⚡ Add all to My Tasks</button>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {autoSteps.map((step, i) => (
              <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.06 }}
                style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', background: step.executed ? 'rgba(0,207,255,0.05)' : 'rgba(255,255,255,0.03)', border: `1px solid ${step.executed ? 'rgba(0,207,255,0.2)' : 'rgba(255,255,255,0.07)'}`, borderRadius: '12px', padding: '1rem 1.2rem' }}>
                <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: step.executed ? 'rgba(0,207,255,0.2)' : 'linear-gradient(135deg,#9B7FFF,#00CFFF)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.72rem', fontWeight: 700, flexShrink: 0, color: 'white' }}>
                  {step.executed ? '✓' : i + 1}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '0.9rem', fontWeight: 600, color: step.executed ? 'rgba(255,255,255,0.5)' : 'white', textDecoration: step.executed ? 'line-through' : 'none' }}>{step.task_title || step.title}</span>
                    {step.estimated_time && <span style={{ fontSize: '0.68rem', color: '#9B7FFF', background: 'rgba(155,127,255,0.1)', padding: '2px 8px', borderRadius: '99px' }}>⏱ {step.estimated_time}</span>}
                    {step.priority && <span style={{ fontSize: '0.68rem', color: step.priority === 'high' ? '#f87171' : 'rgba(255,255,255,0.3)', background: step.priority === 'high' ? 'rgba(239,68,68,0.1)' : 'rgba(255,255,255,0.04)', padding: '2px 8px', borderRadius: '99px' }}>{step.priority}</span>}
                  </div>
                  {step.description && <p style={{ fontSize: '0.78rem', color: 'rgba(255,255,255,0.35)', lineHeight: 1.55, marginBottom: '4px' }}>{step.description}</p>}
                  {step.deadline && <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.3)' }}>📅 {step.deadline}</div>}
                </div>
                {!step.executed && step.action === 'create_task'
                  ? <button onClick={() => executeAutoStep(step)} style={{ padding: '6px 12px', background: 'rgba(0,207,255,0.08)', border: '1px solid rgba(0,207,255,0.22)', borderRadius: '7px', color: '#00CFFF', fontSize: '0.73rem', cursor: 'pointer', fontWeight: 500, flexShrink: 0 }}>+ Add</button>
                  : step.executed && <span style={{ fontSize: '0.72rem', color: '#00CFFF', flexShrink: 0 }}>Added ✓</span>
                }
              </motion.div>
            ))}
          </div>
        </motion.div>
      )}
      </div>
    </div>
)}
        {/* ════ FOCUS MODE PAGE ════ */}
        {activePage === 'focus' && (
          <div style={{ position: 'relative', minHeight: '100vh', overflow: 'hidden' }}>
            <FloatingPaths position={0.6} />
            <FloatingPaths position={-0.6} />
            <div style={{ position: 'absolute', top: '15%', left: '50%', transform: 'translateX(-50%)', width: '500px', height: '300px', background: 'radial-gradient(ellipse, rgba(155,127,255,0.07) 0%, transparent 70%)', pointerEvents: 'none' }} />

            <div style={{ position: 'relative', zIndex: 2, padding: '2.5rem 2.5rem', maxWidth: '640px', margin: '0 auto' }}>
              <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
                <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', background: 'rgba(155,127,255,0.1)', border: '1px solid rgba(155,127,255,0.22)', borderRadius: '99px', padding: '4px 12px', fontSize: '0.7rem', color: '#9B7FFF', marginBottom: '1rem', letterSpacing: '0.06em', fontWeight: 500 }}>
                  🎯 Focus Mode
                </div>
                <h1 style={{ fontSize: '2rem', fontWeight: 800, letterSpacing: '-0.5px', marginBottom: '0.3rem' }}>Deep Work</h1>
                <p style={{ color: 'rgba(255,255,255,0.35)', fontSize: '0.85rem', marginBottom: '2rem' }}>Eliminate distractions. Work on one thing at a time.</p>
              </motion.div>

              {!focusTask ? (
                <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
                  style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '16px', padding: '1.4rem', backdropFilter: 'blur(20px)' }}>
                  <p style={{ color: 'rgba(255,255,255,0.4)', marginBottom: '1rem', fontSize: '0.88rem', fontWeight: 500 }}>Choose a task to focus on:</p>
                  {pending.length === 0 ? (
                    <div style={{ textAlign: 'center', padding: '2rem', color: 'rgba(255,255,255,0.2)', fontSize: '0.85rem' }}>
                      No pending tasks. <span style={{ color: '#9B7FFF', cursor: 'pointer' }} onClick={() => setActivePage('tasks')}>Add some first →</span>
                    </div>
                  ) : pending.map((task, idx) => {
                    const isOverdue = task.deadline && new Date(task.deadline) < new Date();
                    return (
                      <motion.button key={task.id} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: idx * 0.05 }}
                        onClick={() => { setFocusTask(task); setTimer(0); setTimerRunning(false); }}
                        style={{ display: 'flex', alignItems: 'center', gap: '12px', width: '100%', padding: '12px 14px', background: 'rgba(255,255,255,0.03)', border: `1px solid ${isOverdue ? 'rgba(239,68,68,0.25)' : 'rgba(255,255,255,0.07)'}`, borderRadius: '10px', color: 'white', cursor: 'pointer', marginBottom: '7px', textAlign: 'left', fontSize: '0.88rem', transition: 'all 0.15s' }}
                        onMouseEnter={e => e.currentTarget.style.background = 'rgba(155,127,255,0.08)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.03)'}
                      >
                        <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: isOverdue ? '#ef4444' : '#9B7FFF', flexShrink: 0 }} />
                        <span style={{ flex: 1 }}>{task.title}</span>
                        {task.deadline && <span style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.28)' }}>{new Date(task.deadline).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>}
                        <span style={{ color: '#9B7FFF', fontSize: '0.78rem' }}>→</span>
                      </motion.button>
                    );
                  })}
                </motion.div>
              ) : (
                <motion.div initial={{ opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.4 }}>
                  <div style={{ background: 'rgba(155,127,255,0.06)', border: '1px solid rgba(155,127,255,0.2)', borderRadius: '20px', padding: '2.5rem', textAlign: 'center', marginBottom: '1rem', backdropFilter: 'blur(20px)' }}>
                    <div style={{ fontSize: '0.7rem', color: '#9B7FFF', textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: '0.6rem', fontWeight: 700 }}>Now focusing on</div>
                    <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'white', marginBottom: '0.4rem', lineHeight: 1.3 }}>{focusTask.title}</div>
                    {focusTask.deadline && <div style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.3)', marginBottom: '2.5rem' }}>Due: {new Date(focusTask.deadline).toLocaleString()}</div>}

                    <div style={{ fontSize: '4rem', fontWeight: 900, letterSpacing: '-3px', background: 'linear-gradient(135deg,#9B7FFF,#00CFFF)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: '0.4rem', fontVariantNumeric: 'tabular-nums', animation: timerRunning ? 'timerPulse 2s infinite' : 'none' }}>
                      {formatTime(timer)}
                    </div>
                    <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.22)', marginBottom: '2rem' }}>
                      {timerRunning ? '● Recording focus time' : timer > 0 ? `Paused at ${formatTime(timer)}` : 'Press Start to begin'}
                    </div>

                    <div style={{ display: 'flex', gap: '10px', justifyContent: 'center', flexWrap: 'wrap' }}>
                      <button onClick={() => setTimerRunning(r => !r)}
                        style={{ padding: '11px 28px', background: timerRunning ? 'rgba(255,255,255,0.08)' : 'white', color: timerRunning ? 'white' : 'black', border: timerRunning ? '1px solid rgba(255,255,255,0.15)' : 'none', borderRadius: '10px', fontSize: '0.92rem', fontWeight: 700, cursor: 'pointer' }}>
                        {timerRunning ? '⏸ Pause' : '▶ Start'}
                      </button>
                      <button onClick={() => { setTimer(0); setTimerRunning(false); }} style={{ padding: '11px 18px', background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '10px', color: 'rgba(255,255,255,0.4)', fontSize: '0.88rem', cursor: 'pointer' }}>Reset</button>
                      <button onClick={() => completeTask(focusTask.id)} style={{ padding: '11px 18px', background: 'rgba(0,207,255,0.1)', border: '1px solid rgba(0,207,255,0.28)', borderRadius: '10px', color: '#00CFFF', fontSize: '0.88rem', fontWeight: 600, cursor: 'pointer' }}>✓ Done</button>
                    </div>
                  </div>
                  <button onClick={() => { setFocusTask(null); setTimer(0); setTimerRunning(false); }} style={{ width: '100%', padding: '10px', background: 'transparent', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '10px', color: 'rgba(255,255,255,0.22)', fontSize: '0.82rem', cursor: 'pointer' }}>
                    ← Choose a different task
                  </button>
                </motion.div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}